### ISSUE TITLE
[Suggestion] Using instanceof instead of type to determine action

### ISSUE THREAD

**Issue by DmitryEfimenko** [ngrx/example-app#110]
[One of the tutorials on Angular University](http://blog.angular-university.io/angular-2-application-architecture-building-applications-using-rxjs-and-functional-reactive-programming-vs-redux/) suggests using in the reducer `instanceof` instead of the property `type` to determine action:
```ts
function calculateTodos(state: List, action) {
    if (!state) {
        return List([]);
    }
    if (action instanceof  LoadTodosAction) {
        return List(action.todos);
    }
    else if (action instanceof AddTodoAction) {
        return state.push(action.newTodo);
    }
    else if (action instanceof ToggleTodoAction) {
        return toggleTodo(state, action);
    }
    else if (action instanceof DeleteTodoAction) {
        let index = state.findIndex((todo) => todo.id === action.todo.id);
        return state.delete(index);
    }
    else {
        return state;
    }
}
```
This makes sense to me for few reasons:
* you do not need to maintain list of `ActionTypes`
* for the reason above, writing action becomes shorter:
```ts
export class AddTodoAction {
  constructor(public payload: TodoItem) {}
}
```
* Typescript intellisense is able to figure out the type of `action.payload` based on the instance check.

For the reasons above, shouldn't this become the best practice?
Are there any pitfalls I'm missing?

**Comment by rkrisztian** [comment]
I agree that currently adding a new action is more work than one could desire. The benefit of strong type checking is also the disadvantage against being concise. Or not so much, as one advantage of `switch` is that it keeps the conditions concise, i.e. not having to repeat the `action.type ==` or `action instanceof` in your case. So they kind of work against each other. :(

However, you cannot omit `Action.type`,  because it is not an optional field of the interface. Also, Redux DevTools will display the type as a string, which in case of `ActionTypes.SEARCH` is a nicely readable `[Book] Search`.

Regardless, the `instanceof` way can work, but I would drop all the `else` keywords, because usually reducers are so simple that each case just returns the new state (no accidental falls through).

**Comment by vladimiry** [comment]
instanceof approach can be used with switch

```javascript
import {Config} from "@model";
import {ConfigActions, ConfigGetSuccessAction} from "../actions/config.actions";

export function configReducer(state: Config, action: ConfigActions): Config {
    switch (action.constructor) {
        case ConfigGetSuccessAction: {
            return (action as ConfigGetSuccessAction).config;
        }
        default: {
            return state;
        }
    }
}
```

but even though `@ngrx/effects/Actions.ofType` method requires string type.
