### ISSUE TITLE
How to catch errors from @Effects

### ISSUE THREAD

**Issue by bfwg** [ngrx/example-app#132]
Hey, loving your work on the ngrx/store and this example-app.

I have a quick question regarding error handling in @Effects.
In the below code from the example-app. It is calling a `LoadFailAction` when the load collection failed.  I want to catch the this time error from the UI/Component layer. What's the best way to do it?
```javascript
  @Effect()
  loadCollection$: Observable<Action> = this.actions$
    .ofType(collection.ActionTypes.LOAD)
    .startWith(new collection.LoadAction())
    .switchMap(() =>
      this.db.query('books')
        .toArray()
        .map((books: Book[]) => new collection.LoadSuccessAction(books))
        .catch(error => of(new collection.LoadFailAction(error)))  // <-- catch this from the UI layer
    );
```
I thought about creating another `error` state in the collection reducer. But then the error state will be persistence/sticky which is not what I wanted. 

Currently, I'm using something like this in the UI component:
```javascript
  loadCollectionError$: Observable<any>;

  // in ngOnInit
  this.loadCollectionError$ = this.collectionEffects.loadCollection$
  .filter(res => res.type === collection.ActionTypes.LOAD_FAIL)

  this.loadCollectionError$  
  .subscribe(error => {
    console.log(error);
  });

```
Is this the correct way to do it?

Thanks.

**Comment by JohnGallego** [comment]
I don't see an issue with how you are handling it, just be sure to unsubscribe on destroy.

I'm not sure what you're doing with the error, but it might also be a good idea to just create a new set of effects listening for these types of actions with some common purpose in mind. For example, I have a user-error-effects  that listens for particular error actions dispatched by other unrelated effects, logs them, and uses a service to pop a message up to the user. It's nice to have that common bit of functionality in one place, rather than having error displaying/logging logic all over your components.

**Comment by bfwg** [comment]
@JohnGallego 
I noticed an issue when subscribing to @Effects. If you are running cold observables service in the effect, a subscriber will invoke that service. For example: if I'm making a http request in the LOAD effect, it will get invoked when I dispatch an action, but it will also get invoked when I have an error handler subscribing to it. So instead one http request, there will be two.

**Comment by krjordan** [comment]
@bfwg you might be better served asking your question on [gitter](https://gitter.im/ngrx/effects).

**Comment by thienedits** [comment]
@JohnGallego I am getting an error `TypeError: Cannot read property 'open' of undefined`

**Comment by thienedits** [comment]
nvm I figured it out. I was extending an effects class and did not pass in snackbar in both classes
