### ISSUE TITLE
How is the initial data loaded in the live example app?

### ISSUE THREAD

**Issue by niamleeson** [ngrx/example-app#149]
I apologize if the answer to my question is easy to find. I'm kind of confused as to how the app is loading book previews in the collection when the app first loads. There doesn't seem to be a guard like book detail route. Thank you for your help.

**Comment by brandonroberts** [comment]
It's loaded from this effect: https://github.com/ngrx/example-app/blob/master/src/app/effects/collection.ts#L37-L50

The `startWith` operator triggers the action immediately instead of waiting for that action to be dispatched. You could also just dispatch the load action from the container component in the `ngOnInit`

**Comment by niamleeson** [comment]
Thank you!
