### ISSUE TITLE
Examples won't start - Angular/Core index has no exported member 'ModuleWithProviders'

### ISSUE THREAD

**Issue by MarkPieszak** [ngrx/example-app#33]
```
[default] Checking started in a separate process...
[default] /Users/markpieszak/GitHub/ngrx-example/node_modules/@ngrx/store/ng2.d.ts:5:23

Module '"/Users/markpieszak/GitHub/ngrx-example/node_modules/@angular/core/index"' 
    has no exported member 'ModuleWithProviders'.
```

Just got a fresh repo again, and for some reason `npm start` stops at this point - server never spins up. Just putting it up here incase anyone else has ran into it?

**Comment by MarkPieszak** [comment]
Closing out - just a TS error, actually able to run the project now. Apologies.

**Comment by smith64fx** [comment]
@MarkPieszak what did you do to solve this issue?

**Comment by MarkPieszak** [comment]
@smith64fx The TS error is still there but the server still works and fires up, if you scroll up you can see the port and everything. Minor TS issue I'm sure.

**Comment by smith64fx** [comment]
That's not a good solution to ignore it. I found the problem. 

In the package.json I had:
```
"@ngrx/store": "^2.0.1"
```

Now ngrx was automatically updated to 2.0.2, which is only supported by Angular RC5.

Now you have 2 possibilities:
1. Update to RC5. You don't have to change.
2. If you don't want to update, just change the line to this:
```
"@ngrx/store": "2.0.1"
```

To be sure, also do this: 
```
npm i --save @ngrx/store@2.0.1
```


Best Regards,
Michael

**Comment by MarkPieszak** [comment]
Wow very nice!! That'll do it :)

**Comment by omeryounus** [comment]
you need downgrading ngrx/store and effects

ModuleWithProviders is used in ngrx/store since this commit: Link14

Switched to ngrx/store@2.1.0 und ngrx/effects@1.0.0:
`
npm uninstall @ngrx/store --save
npm uninstall @ngrx/effects --save

Install:
npm install @ngrx/store@2.0.1 --save 
npm install @ngrx/effects@1.0.0 --save

If this still doesn't work, try to manually delete the store and effects folders under node_modules/ and uninstall and install again.

Hope this will work for you,
