### ISSUE TITLE
@effect() loadCollectionOnInit$ utility

### ISSUE THREAD

**Issue by lanlau** [ngrx/example-app#36]
Hi, 
i'm starting to learn ngrx and the Side effect model. while reviewing this example app i can't figure out what is the meaning of the following effects in /src/effects/book.ts

@Effect() openDB$ = this.db.open('books_app').filter(() => false);
@Effect() loadCollectionOnInit$ = Observable.of(this.bookActions.loadCollection());

are those effects useful in this example app? why? 
thanks for your help!

**Comment by greglockwood** [comment]
Here is what I understand the purpose of those two seemingly-useless effects to be:

1. Open the `books_app` database on app startup
2. Dispatch the `bookActions.loadCollection()` action on app startup

How do those lines do those functions, you ask? I believe it is because of what the `@Effect` decorator actually does.

The `@Effect()` decorator expects the property to be an `Observable<Action>`. It subscribes to that observable when the app is bootstrapped, and whenever any actions are received, it dispatches them to the store for you. That makes clear how the second effect works.

But what about the first one? Notice that the values emitted by that observable are not actions. In fact, the `.filter(()=>false)` means that no values are received whatsoever (since everything fails the filter). So we have an `Observable` that never fires `.next(), only ever `.completed()`. Which is perfectly valid for an `Observable`. _But_, `@Effect()` subscribes to it nonetheless, which causes the `this.db.open()` call to be made and _actually do something_, and then the observable completes and (I assume) `@Effect()` unsubscribes from it.

I am not a contributor, so I could be wrong, but that is how I understand them to work. Does anybody agree/disagree?

**Comment by btroncone** [comment]
@greglockwood Pretty much nailed it 👍

**Comment by lanlau** [comment]
Thanks a lot for this clear explanation.
