### ISSUE TITLE
How to enable reducers after Latest Update

### ISSUE THREAD

**Issue by willSonic** [ngrx/example-app#37]
For the purpose of my question I will call (reducer/index) -- reducer in main.ts APP_REDUCER . After updates, the app that I have been working on which had implmented the structure of this example-app was working, but after update to Angualr rc5 and latest ngrx... everything broke. 

I have gone through and made the changes, but I have some outstanding issues which I do not understand how to fix..

//latest Ngrx-store... suggest reducers functions are set with ActiveReducer like so
` export const counterReducer: ActionReducer<number> = (state: number = 0, action: Action) =>`

and setting up initiations with 
`StoreModule.provideStore({ counter: counterReducer }, { counter: 0 })`

My problem is that changing my reducer functions from default to const and removing the return of state as in (BookState) ,   and calling StoreModule.provideStore(APP_REDUCER) is now preventing my reducers from establishing initial state.  I am curious as to wether or not folks
*  are changing their reducers to match current ngrx-store documentation using const, not returning state in reducer function...
*  are implementing ActionReducer 
*  are you able to initiate state if you have made these update...

I have been asking these question on gitter.. ngrx/store but have not seem to get any traction .. so any insight would be helpful... Thanks

**Comment by kinggolf** [comment]
Hi @willSonic - did you ever make progress on ngrx store and reducers? I just spent a few days this week upgrading an ng2 app and an ionic2 app to the latest ngrx and ng2 releases. I have been using ngrx/store in 2 production apps since May & I truly love it. It just makes a lot of sense to me for handling state and data, and it's an ideal fit with observable, as the ngrx team has stated and illustrated many times over. My big problem upgrading to the latest was combining reducers when using AoT compiling. This github issue, https://github.com/ngrx/store/issues/190, helped me the most, but it took reading and trials-n-errors many times over before I was able to get things to work.

I have a single reducer file with as many as 35 separate reducers that look like this now:
```
export const UP_ALLEVENTS = 'UP_ALLEVENTS';

function evts (state:AnEvent[], action: Action): AnEvent[] {
    switch (action.type) {
        case UP_ALLEVENTS:
            return action.payload;
        default:
            return state
    }
}
```

Then in the same file I create a rootReducer that is imported in my app.module:
```
const productionReducer = combineReducers({
    trn, admin_action, evts, upselevt, selevtind, sups,
    tcnt, icnt, players, pcnt, scnt, hback, sevent
});

export function rootReducer( state: any, action: any ) {
    return productionReducer( state, action );
}
```

I have been frustrated not getting questions answered on gitter, but same is true on the Ionic2 slack channel. I think everyone is just super busy and there is much to do. So I just keep searching and reading anything I can find to grind through these hurdles.

I really admire the folks who make so much wonderful open source contributions. Without them I would not have my business.

Good luck.

**Comment by MikeRyan52** [comment]
@willSonic Were you able to resolve your issue? If not, feel free to open another issue in the [@ngrx/store](https://github.com/ngrx/store) repo.

Sorry for the late response, The issues opened on the example-app don't get as much attention as they should.
