### ISSUE TITLE
Issues with routing / navigating back & forth

### ISSUE THREAD

**Issue by MarkPieszak** [ngrx/example-app#42]
To repro:
Search for some books, click on one. Then hit back and forth a few times, eventually they all blank out then dissapear.

Not sure what could be causing this in the example, trying to look into it.

```
TypeError: Cannot read property 'id' of undefined
    at BookPreviewComponent.get [as id] (1.chunk.js:246)
    at DebugAppView._View_BookPreviewComponent0.detectChangesInternal 
                         (BookPreviewComponent.template.js:210)
```

**Comment by Uriziel** [comment]
The error appears only when displaying book page.
It's loaded in 3 different ways;

- `Load Book` - accessed through URL

- `Search Complete` - accessed through search

- `Load Collection Success` - accessed through collection saved to `db`

Error will trigger if action that loaded that book will get reverted while its being displayed. Can easily be triggered through dev-tools.

Now, the issue appears because of said dev-tools. As you navigate through app dev-tools will time-travel through all states in app removing action of loading temporarily crashing whole app.
- https://github.com/ngrx/store-devtools/blob/master/src/reducer.ts#L278

Would be nice if @ngrx team could show us how to implement this safely though.

**Comment by MikeRyan52** [comment]
This should be fixed as of the most recent updates. If it persists, feel free to open another issue.
