### ISSUE TITLE
[Question] : What is the use of actionsSubscription

### ISSUE THREAD

**Issue by pocmanu** [ngrx/example-app#50]
First, thanks for this example app, it is a great source of inspiration to help newcomers to nrgx design their own app.

It took me some time to fully understand the structure of Pages/Components regarding to route.

I came up with this small sketch which made it clear, maybe it can help some others (do you plan to start a wiki, at least to put a FAQ ?)

![image](https://cloud.githubusercontent.com/assets/9366309/18775385/92d552c0-8161-11e6-8b4c-81f50689d69b.png)

My question is about ViewBookPageComponent. I understand that we map url parameters to dispatch a SelectedBookAction to the Store.

`    this.actionsSubscription = route.params
      .select<string>('id')
      .map(id => new SelectBookAction(id))
      .subscribe(store);
`

I first thought that keeping a track of the subscription and calling `this.actionsSubscription.unsubscribe();` on destroy was a way to free the store from watching the observable but then I read the [Rx.Subscription description](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/testing/subscription.md) and knowing that unsubscribe() is only a getter for 

> the unsubscription virtual time

I don't see the interest of calling it on destroy.

Can you enlighten me about it ?

**Comment by greglockwood** [comment]
You have made the very common mistake of looking at the docs for RxJS v4, rather than v5 (Next), which is the version used by Angular 2 and @ngrx modules.

The correct documentation for v5 is at http://reactivex.io/rxjs/

[Here is the link](http://reactivex.io/rxjs/class/es6/Subscription.js~Subscription.html#instance-method-unsubscribe) to the `unsubscribe()` documentation, which states:

> Disposes the resources held by the subscription. May, for instance, cancel an ongoing Observable execution or cancel any other type of work that started when the Subscription was created.

This is the equivalent to calling `subscription.dispose()` in RxJS v4. Hopefully the need to call `.unsubscribe()` is now clear.

**Comment by pocmanu** [comment]
Thank you for pointing me to the right documentation, I save it for further use.

It makes much more sense now because it does what I naturally thought it should do.
