### ISSUE TITLE
Effect decorator return type

### ISSUE THREAD

**Issue by metanav** [ngrx/example-app#56]
In example app:
  @Effect() search$: Observable<**Action**> = this.actions$

In ngrx/effects API examples:
 @Effect() login$: Observable<**Actions**> = this.actions$

Which is correct:  Observable<**Action**> or  Observable<**Actions**>?

**Comment by br1anchen** [comment]
Hi,

I think the return type of `@Effect()` method is better to be `Observable<Action>` here,
it is the same in [Epics](https://github.com/redux-observable/redux-observable/blob/master/docs/basics/Epics.md), actions in and actions out, as long as `Epic` or `Effect` return Observable, it will fit the requirement. The generic type here is to indicate what kind of stream is that.
I think we are expecting `Observable<Action>` rather than `Observable<Actions>`, since we only care about individual emitted action in pure functional `reducer`.

If you have a look about type definition of `actions.d.ts` and `action.d.ts`, `Actions` extends from `Action` with some more helper methods. So it will not matter for `tsc` to differ either of them.

That is my opinion of course.
